name: admin-ui-trunk
namespace: official
version: 1.1.0
author: Wazo Team
display_name: Trunks
min_wazo_version: 17.17
tags:
  - beta
  - routing
homepage: https://github.com/wazo-pbx/wazo-admin-ui-trunk
depends:
  - name: admin-ui-context
    namespace: official
    version: 1.0.1