name: admin-ui-trunk
namespace: official
version: 1.2.0-2
author: Wazo Team
display_name: Trunks
min_wazo_version: 18.02
tags:
  - routing
homepage: https://github.com/wazo-pbx/wazo-admin-ui-trunk
depends:
  - name: admin-ui-context
    namespace: official
