name: admin-ui-trunk
namespace: official
version: 1.0.0
author: Wazo Team
display_name: Trunks
min_wazo_version: 17.16
tags:
  - beta
  - routing
homepage: https://github.com/wazo-pbx/wazo-admin-ui-trunk
